name: CI/CD Pipeline for Golang Project

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23'  # Specify your Golang version here

    - name: Build Go application
      run: go build -o myapp .  # Build your Go app

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | sudo docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: sudo docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:latest .

    - name: Push Docker image to Docker Hub
      run:  sudo docker push ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:latest

  deploy-to-ec2:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
    - name: SSH into EC2 and Deploy Docker Container
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ${{ secrets.AWS_EC2_USER }}
        key: ${{ secrets.AWS_EC2_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:latest
          docker stop myapp || true
          docker rm myapp || true
          docker run -d --name myapp -p 80:8080 ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:latest
