name: Sync Fork with Main Repository

on:
  push:
    branches:
      - main   # This triggers when there are changes to the `main` branch in repo-1

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo-2 (Your Forked Repository)
      - name: Checkout repo-2 (Your Forked Repository)
        uses: actions/checkout@v2

      # Step 2: Set up Git
      - name: Set up Git
        run: |
          git config user.name "20BQ1A0458"
          git config user.email "20bq1a0458@vvit.net"

      # Step 3: Add upstream remote (repo-1)
      - name: Add upstream remote (repo-1)
        run: |
          git remote remove upstream || true  # Remove if it exists
          git remote add upstream https://github.com/karankumarsahu/wireguard_server_test.git
          git fetch upstream

      # Step 4: Merge changes from repo-1/main into repo-2/main
      - name: Merge changes from repo-1/main into repo-2/main
        run: |
          git checkout main
          git pull upstream main --strategy=recursive --strategy-option=theirs  # Auto-resolve conflicts by keeping upstream changes
          git push origin main     # Push those changes to your forked repository (repo-2)
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Use the secret token to authenticate
