name: Sync with Friend's Repo

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Add Friend's Repo as Remote
        run: git remote add friend_repo https://github.com/karankumarsahu/wireguard_server_test.git

      - name: Fetch and Merge Changes from Friend's Repo
        run: |
          git fetch friend_repo
          git merge friend_repo/main
          
      - name: Push Changes to Repo 2
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
